version: '2'
services:
  app:
    ports:
     - "3000:3000"
    build: .
    environment:
      APP_DATABASE_PASSWORD: "${APP_DATABASE_PASSWORD}"

  db:
    build: ./postgresDocker/
    restart: always
    environment:
      FILLA_DB_USER: "rails"
      FILLA_DB_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_USER: "postgres"
    volumes:
       # Persist the data between container invocations
       - postgresData:/var/lib/postgresql/data
       # Config file
       - ./postgresql.conf:/etc/postgresql.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  postgresData:
